language: android

install: true

sudo: true

notifications:
  email: false

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools # duplicated on purpose as it’s required to get the newest Android SDK tools.

    # SDK version to compile project
    - android-28

script: "./deploy.sh"

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
  - ".gradle"
